name: CI

on:
  push:
    branches:
      - page
      - 'feature/**'
      - 'bugfix/**'
  pull_request:
    branches:
      - page

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Wybierz wersję Node.js zgodną z Twoim projektem

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build

    - name: Run tests
      run: npm run test

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: vue-build
        path: dist/
